using System.Collections.Generic;
using System.IO;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace SoDArchipelago
{
    // Item/location table shared with the apworld. Generated by tools/extract_game_data.py and embedded at build time.
    public static class GameData
    {
        public const string GameName = "Shape of Dreams";

        public class Item
        {
            public long Id;
            public string Name;
            public string Key;
            public string Kind; // progressive, memory, essence, lucid_dream, mastery, stardust, blessing, treasure, curse
            public string Target; // vanilla modifier, Treasure prefab or curse tier
            public string Traveler; // progressive and mastery items
            public List<string> Unlocks; // unlock items: the targets, in unlock order (progressive: one per copy)
            public List<string> UnlockNames; // progressive items: display names of Unlocks
        }

        public class Location
        {
            public long Id;
            public string Name;
            public string Key;
            public string Kind; // achievement, world_clear, souvenir, ware, shrine, quest, artifact
            public int Number; // sequential Jonas ware number
            public string Traveler;
            public int World;
            public string Difficulty;
        }

        public class Traveler
        {
            public string Key;
            public string Name;
            public string ProgressiveItem;
            public string MasteryItem;
            public List<string> Skills; // every Q/R/Identity memory (base and alternate)
            public List<string> AltMemories; // the achievement-locked ones, in progressive order
        }

        public class Difficulty
        {
            public string Key;
            public string Name;
            public string GameId;
            public int Rank;
            public bool HasLocations;
        }

        public static int DataFormatVersion { get; private set; }
        // Fingerprint of the IDs, keys and logic data (apworld data/data_hash.py). Must equal the seed's slot_data.
        public static string DataHash { get; private set; }
        public static string ExtractedFromGameVersion { get; private set; }

        // Worlds whose clear is detected by moving on to the next zone (a loop has 4 worlds). World 5 is Primus, cleared
        // by a Pure White Dream win (DESIGN.md "World structure").
        public const int NormalWorlds = 4;
        public const int PrimusWorld = 5;

        public static readonly Dictionary<long, Item> ItemsById = new Dictionary<long, Item>();
        public static readonly Dictionary<string, Item> ItemsByKey = new Dictionary<string, Item>();
        public static readonly Dictionary<string, Location> LocationsByKey = new Dictionary<string, Location>();
        public static readonly Dictionary<string, Traveler> Travelers = new Dictionary<string, Traveler>();
        public static readonly List<Difficulty> Difficulties = new List<Difficulty>();
        // The lizard shop souvenir locations; their keys are the Accessory names (DESIGN.md "Souvenirs").
        public static readonly List<Location> Souvenirs = new List<Location>();
        public static readonly List<Location> Artifacts = new List<Location>();

        // Every vanilla achievement unlock target (Hero_*, St_*, Gem_*, LucidDream_*). On a marked profile these are
        // unlocked only by AP items.
        public static readonly HashSet<string> UnlockTargets = new HashSet<string>();

        public const string StardustKey = "STARDUST";

        public static void Load()
        {
            ItemsById.Clear();
            ItemsByKey.Clear();
            LocationsByKey.Clear();
            Travelers.Clear();
            Difficulties.Clear();
            Souvenirs.Clear();
            Artifacts.Clear();
            UnlockTargets.Clear();

            var asm = typeof(GameData).Assembly;
            using var stream = asm.GetManifestResourceStream("SoDArchipelago.game_data.json");
            using var reader = new StreamReader(stream);
            var root = JObject.Parse(reader.ReadToEnd());

            DataFormatVersion = (int)root["data_format_version"];
            DataHash = (string)root["data_hash"];
            ExtractedFromGameVersion = (string)root["extracted_from_game_version"];

            foreach (var e in root["items"])
            {
                var item = new Item
                {
                    Id = (long)e["id"],
                    Name = (string)e["name"],
                    Key = (string)e["key"],
                    Kind = (string)e["kind"],
                    Target = (string)e["target"],
                    Traveler = (string)e["traveler"],
                    Unlocks = e["unlocks"]?.Select(u => (string)u).ToList() ?? new List<string>(),
                    UnlockNames = e["unlock_names"]?.Select(u => (string)u).ToList(),
                };
                ItemsById[item.Id] = item;
                ItemsByKey[item.Key] = item;
                foreach (var target in item.Unlocks) UnlockTargets.Add(target);
            }

            foreach (var e in root["locations"])
            {
                var loc = new Location
                {
                    Id = (long)e["id"],
                    Name = (string)e["name"],
                    Key = (string)e["key"],
                    Kind = (string)e["kind"],
                    Traveler = (string)e["traveler"],
                    World = (int?)e["world"] ?? 0,
                    Number = (int?)e["number"] ?? 0,
                    Difficulty = (string)e["difficulty"],
                };
                LocationsByKey[loc.Key] = loc;
                if (loc.Kind == "souvenir") Souvenirs.Add(loc);
                if (loc.Kind == "artifact") Artifacts.Add(loc);
            }

            foreach (var e in root["travelers"])
            {
                var t = new Traveler
                {
                    Key = (string)e["key"],
                    Name = (string)e["name"],
                    ProgressiveItem = (string)e["progressive_item"],
                    MasteryItem = (string)e["mastery_item"],
                    Skills = e["skills"].Select(s => (string)s).ToList(),
                };
                var progressive = ItemsByKey["PROGRESSIVE_" + t.Key];
                t.AltMemories = progressive.Unlocks.Where(u => u != t.Key).ToList();
                Travelers[t.Key] = t;
            }

            foreach (var e in root["difficulties"])
            {
                Difficulties.Add(new Difficulty
                {
                    Key = (string)e["key"],
                    Name = (string)e["name"],
                    GameId = (string)e["game_id"],
                    Rank = (int)e["rank"],
                    HasLocations = (bool)e["has_locations"],
                });
            }
        }

        // Rank of a GameSettingsManager.difficulty / DewGameResult.difficulty id, or -1 when it isn't one of the four
        // (Limbo, the tutorial, anything new).
        public static int RankOfGameDifficulty(string gameId)
        {
            foreach (var d in Difficulties)
                if (d.GameId == gameId) return d.Rank;
            return -1;
        }

        public static string WorldClearKey(int world, string difficultyKey, string travelerKey) =>
            $"CLEAR_W{world}_{difficultyKey}_{travelerKey}";
    }
}
